checking before de-bloincking

diff --git a/check b/check
--- a/check
+++ b/check
@@ -4,17 +4,35 @@ debug() {
 	[ -n "$DEBUG" ] && echo "$*"
 }
 
+usage(){
+	(
+	echo "Usage: $0 [--rename|--delete] machine/block_dev/yyyy-mm-dd__hh-mm-ss/"
+	echo "--rename: rename corrupted chunks (default)"
+	echo "--delete: delete corrupted chunks"
+	# TODO : echo "--replace: with older chunk"
+	# TODO : echo "--replace-zeros: replace with zeros"
+	while [ -n "$1" ]; do
+		echo "$1"
+		shift
+	done
+	) >&2
+
+}
+
+# CMD
+PLDEZIP="plzip -q -c -d "
 SUMCMD='sha256sum'
 DELETE=""
 RENAME="yes"
 
 while [ -n "$1" ]; do
 	case "$1" in
+		"--rename" ) RENAME="yes"; DELETE="" ;;
 		"--delete" ) RENAME=""; DELETE="-delete" ;;
 		* )
 			DEV_SNAPSHOT="$1"
 			if [ ! -d "$DEV_SNAPSHOT" ]; then
-				echo "Cannot check un-existing snapshot"
+				usage "Cannot check un-existing snapshot"
 				exit 1
 			fi
 		;;
@@ -24,36 +42,38 @@ done
 
 
 if [ -n "$( find "$DEV_SNAPSHOT" -name "*.lzma" )" ]; then
-for BLOCK_FILE in "$DEV_SNAPSHOT"/*".lzma"; do
+	for BLOCK_FILE in $(find . -name "$DEV_SNAPSHOT"/*".lzma" | sort ); do
 
-	F="$(basename "$BLOCK_FILE" ".lzma")"
-	FILE_PAD="${F%%_*}"
-	FILE_SUM="${F##*_}"
+		F="$(basename "$BLOCK_FILE" ".lzma")"
+		FILE_PAD="${F%%_*}"
+		FILE_SUM="${F##*_}"
 
-	ERROR=""
-	if [ -z "$FILE_PAD" ]; then ERROR="$ERROR No File Pad"; fi
-	if [ -z "$FILE_SUM" ]; then ERROR="$ERROR No File Sum"; fi
+		ERROR=""
+		if [ -z "$FILE_PAD" ]; then ERROR="$ERROR No File Pad"; fi
+		if [ -z "$FILE_SUM" ]; then ERROR="$ERROR No File Sum"; fi
 
-	if [ -z "$ERROR" ]; then
-		SUM="$(plzip -d -c "$BLOCK_FILE" | $SUMCMD | tr -d ' -')"
+		if [ -z "$ERROR" ]; then
+			SUM="$($PLDEZIP "$BLOCK_FILE" | $SUMCMD | tr -d ' -')"
 
-		if [ "$SUM" != "$FILE_SUM" ]; then ERROR="$ERROR Incorrect Sum"; fi
-	fi
-
-	if [ ! -z "$ERROR" ]; then
-		echo "$BLOCK_FILE - $ERROR"
-
-		if [ -n "$RENAME" ]; then
-			mv "$BLOCK_FILE" "$BLOCK_FILE.incorrect"
-			BLOCK_FILE="$BLOCK_FILE"".incorrect"
+			if [ "$SUM" != "$FILE_SUM" ]; then ERROR="$ERROR Incorrect Sum"; fi
 		fi
 
-		DEV_FOLDER="$(dirname "$DEV_SNAPSHOT")"
-		find "$DEV_FOLDER" -xdev -samefile "$BLOCK_FILE" \! -name "*.lzma.incorrect" $DELETE
-	fi
+		if [ ! -z "$ERROR" ]; then
+			echo "$BLOCK_FILE - $ERROR"
 
-done
+			if [ -n "$RENAME" ]; then
+				mv "$BLOCK_FILE" "$BLOCK_FILE.incorrect"
+				BLOCK_FILE="$BLOCK_FILE"".incorrect"
+			fi
+			if [ -z "$DELETE" ]; then
+				RENAME_ARG="-exec mv \{\} \{\}.incorrect \;"
+			fi
+
+			find . -xdev -samefile "$BLOCK_FILE" \! -name "*.lzma.incorrect" $DELETE $RENAME_ARG
+		fi
+
+	done
 else
-	echo "Cannot check un-existing snapshot files"
+	usage "Cannot check un-existing snapshot files"
 fi
 
diff --git a/de-bloinck b/de-bloinck
--- a/de-bloinck
+++ b/de-bloinck
@@ -1,23 +1,65 @@
 #!/bin/bash
 
 debug() {
-	[ -n "$DEBUG" ] && echo "$*"
+	[ -n "$DEBUG" ] && echo "$*" >&2
 }
 
-DEV_SNAPSHOT="$1"
-if [ ! -d "$DEV_SNAPSHOT" ]; then
-	echo "Cannot de-bloinck un-existing snapshot"
-	exit 1
-fi
+usage(){
+	(
+	echo "Usage: $0 [--check|--no-check] machine/block_dev/yyyy-mm-dd__hh-mm-ss/ > dest_file"
+	echo "--check: verify checksum before decompressing (default)"
+	echo "--no-check: skip verification of checksum"
+	while [ -n "$1" ]; do
+		echo "$1"
+		shift
+	done
+	) >&2
 
-# TODO: we should check that we have all the chuncks before starting to decompress
+}
+
+# CMD
+PLDEZIP="plzip -q -c -d "
+SUMCMD='sha256sum'
+
+CHECK="yes"
+DEV_SNAPSHOT=""
+
+while [ -n "$1" ]; do
+
+	case "$1" in
+		"-c" | "--check" )	CHECK="yes";;
+		"-nc" | "--no-check" )	CHECK="";;
+		* )
+		DEV_SNAPSHOT="$1"
+		if [ ! -d "$DEV_SNAPSHOT" ]; then
+			usage "Cannot de-bloinck un-existing snapshot"
+			exit 1
+		fi
+		;;
+	esac
+	shift
+done
+
+
+# TODO: we should check that we have all the chuncks before starting to decompress and that they are OK
 # 
 
 if [ -n "$(find . -name "$DEV_SNAPSHOT"/*".lzma" )" ]; then
-for BLOCK_FILE in "$DEV_SNAPSHOT"/*".lzma"; do
-	plzip -d -c "$BLOCK_FILE"
-done
+
+	if [ -n "$CHECK" ]; then
+		for BLOCK_FILE in $(find . -name "$DEV_SNAPSHOT"/*".lzma" | sort ); do
+			SUM="$($PLDEZIP "$BLOCK_FILE" | $SUMCMD | tr -d ' -')"
+			if [ "${BLOCK_FILE//$SUM/}" == "$BLOCK_FILE" ]; then
+				echo "Verification of $BLOCK_FILE failed, you should run the 'check' script before decompressing" >&2
+				exit 1
+			fi
+		done
+	fi
+
+	for BLOCK_FILE in $(find . -name "$DEV_SNAPSHOT"/*".lzma" | sort ); do
+		$PLDEZIP "$BLOCK_FILE"
+	done
 else
-	echo "Cannot de-bloinck un-existing snapshot files"
+	usage "Cannot de-bloinck un-existing snapshot files"
 fi
 
